export const TIMEZONES: { value: string; label: string }[] = [
  { value: 'Africa/Abidjan',      label: 'Abidjan (GMT+0)' },
  { value: 'Africa/Accra',        label: 'Accra (GMT+0)' },
  { value: 'Africa/Addis_Ababa',  label: 'Addis Ababa (GMT+3)' },
  { value: 'Africa/Cairo',        label: 'Cairo (GMT+2)' },
  { value: 'Africa/Casablanca',   label: 'Casablanca (GMT+1)' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg (GMT+2)' },
  { value: 'Africa/Lagos',        label: 'Lagos (GMT+1)' },
  { value: 'Africa/Nairobi',      label: 'Nairobi (GMT+3)' },
  { value: 'America/Chicago',     label: 'Chicago (GMT-6)' },
  { value: 'America/Denver',      label: 'Denver (GMT-7)' },
  { value: 'America/Los_Angeles', label: 'Los Angeles (GMT-8)' },
  { value: 'America/New_York',    label: 'New York (GMT-5)' },
  { value: 'America/Sao_Paulo',   label: 'São Paulo (GMT-3)' },
  { value: 'America/Toronto',     label: 'Toronto (GMT-5)' },
  { value: 'Asia/Colombo',        label: 'Colombo (GMT+5:30)' },
  { value: 'Asia/Dubai',          label: 'Dubai (GMT+4)' },
  { value: 'Asia/Karachi',        label: 'Karachi (GMT+5)' },
  { value: 'Asia/Kolkata',        label: 'Mumbai / Kolkata (GMT+5:30)' },
  { value: 'Asia/Singapore',      label: 'Singapore (GMT+8)' },
  { value: 'Asia/Tokyo',          label: 'Tokyo (GMT+9)' },
  { value: 'Australia/Melbourne', label: 'Melbourne (GMT+10)' },
  { value: 'Australia/Sydney',    label: 'Sydney (GMT+10)' },
  { value: 'Europe/Amsterdam',    label: 'Amsterdam (GMT+1)' },
  { value: 'Europe/Berlin',       label: 'Berlin (GMT+1)' },
  { value: 'Europe/London',       label: 'London (GMT+0)' },
  { value: 'Europe/Madrid',       label: 'Madrid (GMT+1)' },
  { value: 'Europe/Paris',        label: 'Paris (GMT+1)' },
  { value: 'Pacific/Auckland',    label: 'Auckland (GMT+12)' },
]
